using System;
using System.Web.UI;
using EPiServer.Core;
using EPiServer.DynamicContent;

namespace DOC.Intranet.AlloyDemo.DynamicContent
{
    [DynamicContentPlugIn(
        DisplayName = "UserControlDynamicContentPlugin",
        Description = "Example of a Dynamic Content plugin as a user control.")]
    public partial class UserControlDynamicContentPlugin : UserControl, IDynamicContentDisplayType
    {
        // Properties of the following basic types that have public getters
        // and setters are supported by the autogenerated edit interface.
        public string MyString { get; set; }
        public int MyInt { get; set; }
        public bool MyBool { get; set; }

        // The same is true for EPiServer.Core.PageReference...
        public PageReference MyPageReference { get; set; }

        // ...and types inheriting from EPiServer.Core.PropertyData,
        // illustrated here with PropertyString.
        public PropertyString MyPropertyString { get; set; }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                DataBind();
            }
        }

        public bool RenderAsBlockElement
        {
            get { return false; }
        }
    }
}